CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    username   VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

DO
$$
BEGIN
    IF
    NOT EXISTS (
            SELECT 1
            FROM information_schema.table_constraints
            WHERE constraint_name = 'uc_users_username'
              AND table_name = 'users'
        ) THEN
    ALTER TABLE users
        ADD CONSTRAINT uc_users_username UNIQUE (username);
    END IF;
END $$;


DO
$$
BEGIN
    IF
NOT EXISTS (
        SELECT 1
        FROM users
        WHERE username = 'root'
    ) THEN
        INSERT INTO users (username, password, created_at, updated_at)
        VALUES ('root', '$2a$10$oVkacG9mPYdjw.40BRed.ejvmKLIdpbyHQVDgy.mP3gtHwEq2bDmO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
END IF;
END $$;